# Copyright (c) egakareta <team@egakareta.com>.
# Licensed under the GNU AGPLv3 or a proprietary Commercial License.
# See LICENSE and COMMERCIAL.md for details.
[toolchain]
channel = "nightly-2026-03-12"
components = ["rustfmt", "clippy", "llvm-tools-preview", "rust-src"]
targets = ["wasm32-unknown-unknown"]
