-- Create a table for public profiles which extends the auth.users table.
-- Most user-facing information is stored here.
create table if not exists profiles (
    -- Links to Supabase Auth
    id uuid references auth.users on delete cascade not null primary key,
    -- Sequential numeric ID for display purposes (e.g., profile/123)
    number_id bigint generated always as identity unique,
    updated_at timestamp with time zone,
    last_seen_at timestamp with time zone default timezone('utc', now()),
    -- Unique display name
    username text unique,
    avatar_url text,
    website text,
    bio text not null default '',
    -- ISO Country Code (e.g., 'US', 'JP')
    country text not null default 'UN',
    joined_at date not null default (timezone('utc', now()))::date,
    follower_count integer not null default 0,
    -- User ranking tier
    mapper_tier text not null default 'New Mapper' check (
        mapper_tier in ('New Mapper', 'Nominator', 'Ranked Mapper')
    ),
    is_admin boolean not null default false,
    muted_until timestamp with time zone,
    banned_until timestamp with time zone,
    favorite_mods text [] not null default '{}',
    constraint username_length check (
        char_length(username) >= 3
        and char_length(username) <= 24
    ),
    -- Alphanumeric and underscores only
    constraint username_format check (username ~ '^[a-zA-Z0-9_]+$')
);
-- Create profile_stats table to track performance metrics separate from profile metadata.
create table if not exists public.profile_stats (
    profile_id uuid primary key references public.profiles(id) on delete cascade,
    -- Performance Points
    total_pp integer not null default 0,
    -- Cumulative score from ranked maps
    ranked_score bigint not null default 0,
    maps_cleared integer not null default 0,
    global_rank integer,
    country_rank integer,
    updated_at timestamp with time zone default timezone('utc', now()) not null
);
-- Create a table for beatmaps (the playable content of the game).
create table if not exists beatmaps (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    ranked_at timestamp with time zone,
    -- Map name
    name text not null,
    -- Song title
    title text not null,
    -- Song artist
    artist text not null,
    mapper_id uuid references profiles(id) not null,
    description text,
    -- Original beatmap metadata creator field
    creator text not null default '',
    -- Metadata difficulty value from EGZ
    difficulty double precision not null default 0,
    -- R2 object key for the audio file in beatmap-audio
    audio_url text not null,
    -- R2 object key for parquet beatmap data in beatmap-data
    data_url text not null,
    -- Original metadata source file for music (typically audio.mp3)
    music_source text not null default '',
    -- Music start offset in seconds
    music_start_seconds double precision not null default 0,
    -- Unicode metadata fields for display/i18n support
    music_unicode_author text not null default '',
    music_unicode_title text not null default '',
    -- Spawn position from metadata.spawn.position [x, y, z]
    spawn_position double precision [] not null default array [0.0, 0.0, 0.0]::double precision [],
    -- Timeline duration from metadata.timeline_duration_seconds
    timeline_duration_seconds double precision not null default 0,
    status text default 'UNRANKED' check (status in ('UNRANKED', 'RANKED', 'OFFICIAL')),
    plays integer default 0,
    downloads integer default 0,
    likes integer default 0,
    length_seconds integer not null default 0,
    bpm integer not null default 0,
    nominator_stars numeric(4, 2) not null default 0,
    community_stars numeric(4, 2) not null default 0,
    constraint beatmaps_spawn_position_dimensions check (array_length(spawn_position, 1) = 3)
);
-- Categorization for beatmaps to improve searchability.
create table if not exists public.beatmap_tags (
    id uuid default gen_random_uuid() primary key,
    beatmap_id bigint not null references public.beatmaps(id) on delete cascade,
    tag text not null,
    unique (beatmap_id, tag)
);
-- Records play results and calculates Performance Points.
create table if not exists public.beatmap_scores (
    id uuid default gen_random_uuid() primary key,
    beatmap_id bigint not null references public.beatmaps(id) on delete cascade,
    profile_id uuid references public.profiles(id) on delete
    set null,
        -- Display name at the time of play
        player_handle text not null,
        score bigint not null,
        -- Performance points awarded
        pp integer not null,
        -- Game modifiers (e.g., '{HD,DT}')
        mods text [] not null default array []::text [],
        played_at timestamp with time zone default timezone('utc', now()) not null
);
-- Threaded comments system for beatmaps and news posts.
create table if not exists public.comments (
    id uuid default gen_random_uuid() primary key,
    -- Resource type this comment belongs to.
    resource_type text not null check (resource_type in ('beatmap', 'news_post')),
    -- Resource ID in string form. (beatmap ID or news slug)
    resource_id text not null,
    -- For nested replies
    parent_id uuid references public.comments(id) on delete cascade,
    profile_id uuid references public.profiles(id) on delete
    set null,
        body text not null,
        -- Denormalized vote count updated by triggers
        votes integer not null default 0,
        created_at timestamp with time zone default timezone('utc', now()) not null,
        updated_at timestamp with time zone
);
-- Tracks individual votes (-1 or 1) on comments.
create table if not exists public.comment_votes (
    id UUID default gen_random_uuid() primary key,
    comment_id UUID not null references public.comments(id) on delete cascade,
    user_id UUID not null references auth.users(id) on delete cascade,
    -- Limited to upvote (+1) or downvote (-1)
    vote SMALLINT not null check (vote in (-1, 1)),
    created_at TIMESTAMP with TIME ZONE default timezone('utc', now()) not null,
    unique(comment_id, user_id) -- Ensures one vote per user per comment
);
-- Table to capture daily snapshots of profile ranks and PP for historical tracking and trends analysis.
create table if not exists public.profile_rank_pp_snapshots (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    snapshot_date date not null default (timezone('utc', now()))::date,
    global_rank integer,
    country_rank integer,
    total_pp integer not null,
    created_at timestamp with time zone default timezone('utc', now()) not null,
    unique (profile_id, snapshot_date)
);
-- Table for 2FA configuration and TOTP
create table if not exists public.user_2fa_config (
    user_id uuid primary key references auth.users(id) on delete cascade,
    totp_secret text,
    totp_enabled boolean not null default false,
    webauthn_enabled boolean not null default false,
    backup_codes text [] not null default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    current_challenge text
);
-- Table for WebAuthn credentials
create table if not exists public.user_webauthn_credentials (
    id text primary key,
    -- credentialID (base64url)
    user_id uuid not null references auth.users(id) on delete cascade,
    public_key bytea not null,
    counter bigint not null default 0,
    transports text [] not null default '{}',
    created_at timestamp with time zone default now()
);
-- Short-lived browser-to-native authentication handoffs.
create table if not exists public.auth_handoffs (
    id uuid default gen_random_uuid() primary key,
    secret_hash text not null,
    auth_payload jsonb,
    profile_id uuid references public.profiles(id) on delete set null,
    created_at timestamp with time zone default timezone('utc', now()) not null,
    expires_at timestamp with time zone default timezone('utc', now()) + interval '10 minutes' not null,
    claimed_at timestamp with time zone
);

create or replace function public.claim_auth_handoff(
    claim_id uuid,
    claim_secret_hash text
) returns jsonb language plpgsql security definer
set search_path = public as $$
declare
    payload jsonb;
begin
    select auth_payload into payload
    from public.auth_handoffs
    where id = claim_id
        and secret_hash = claim_secret_hash
        and claimed_at is null
        and expires_at > timezone('utc', now())
        and auth_payload is not null
    for update;

    if payload is null then
        return null;
    end if;

    update public.auth_handoffs
    set claimed_at = timezone('utc', now()),
        auth_payload = null
    where id = claim_id
        and claimed_at is null
        and auth_payload is not null;

    if not found then
        return null;
    end if;

    return payload;
end;
$$;

create or replace function public.cleanup_auth_handoffs()
returns integer language plpgsql security definer
set search_path = public as $$
declare
    deleted_count integer;
begin
    delete from public.auth_handoffs
    where claimed_at is not null
        or expires_at <= timezone('utc', now());

    get diagnostics deleted_count = row_count;
    return deleted_count;
end;
$$;
-- Enforce security at the database level.
alter table profiles enable row level security;
alter table public.profile_stats enable row level security;
alter table beatmaps enable row level security;
alter table public.beatmap_tags enable row level security;
alter table public.beatmap_scores enable row level security;
alter table public.comments enable row level security;
alter table public.comment_votes ENABLE row level security;
alter table public.profile_rank_pp_snapshots enable row level security;
alter table public.user_2fa_config enable row level security;
alter table public.user_webauthn_credentials enable row level security;
alter table public.auth_handoffs enable row level security;
-- Policies.
-- profiles
create policy "Public profiles are viewable by everyone." on profiles for
select using (true);
create policy "Users can insert their own non-admin profile." on profiles for
insert with check (
        (
            select auth.uid()
        ) = id
        and not is_admin
    );
create policy "Users can update own profile, except for admin status." on public.profiles for
update using (
        (
            select auth.uid()
        ) = id
    ) with check (
        (
            select auth.uid()
        ) = id
        and is_admin = (
            select p.is_admin
            from public.profiles p
            where p.id = (
                    select auth.uid()
                )
        )
    );
revoke insert, update on public.profiles
from anon,
    authenticated;
grant insert (id, username, avatar_url, website, bio, country, favorite_mods) on public.profiles to authenticated;
grant update (username, avatar_url, website, bio, country, favorite_mods, updated_at) on public.profiles to authenticated;
-- profile_stats
create policy "Profile stats are viewable by everyone." on public.profile_stats for
select using (true);
create policy "Service role can manage profile stats." on public.profile_stats for all to service_role using (true) with check (true);
-- beatmaps
create policy "Beatmaps are viewable by everyone." on beatmaps for
select using (true);
create policy "Users can upload their own unranked beatmaps." on beatmaps for
insert with check (
        (
            select auth.uid()
        ) = mapper_id
        and status = 'UNRANKED'
    );
create policy "Users can update their own unranked beatmaps." on beatmaps for
update using (
        (
            select auth.uid()
        ) = mapper_id
        and status = 'UNRANKED'
    );
revoke insert, update on public.beatmaps
from anon,
    authenticated;
grant insert (
    name,
    title,
    artist,
    mapper_id,
    description,
    creator,
    difficulty,
    audio_url,
    data_url,
    music_source,
    music_start_seconds,
    music_unicode_author,
    music_unicode_title,
    spawn_position,
    timeline_duration_seconds,
    length_seconds,
    bpm
) on public.beatmaps to authenticated;
grant update (
    name,
    title,
    artist,
    description,
    creator,
    difficulty,
    audio_url,
    data_url,
    music_source,
    music_start_seconds,
    music_unicode_author,
    music_unicode_title,
    spawn_position,
    timeline_duration_seconds,
    length_seconds,
    bpm,
    updated_at
) on public.beatmaps to authenticated;
-- beatmap_tags
create policy "Beatmap tags are viewable by everyone." on public.beatmap_tags for
select using (true);
create policy "Mappers can insert tags for their maps." on public.beatmap_tags for
insert with check (
        exists (
            select 1
            from public.beatmaps b
            where b.id = beatmap_tags.beatmap_id
                and b.mapper_id = (
                    select auth.uid()
                )
                and b.status = 'UNRANKED'
        )
    );
create policy "Mappers can update tags for their maps." on public.beatmap_tags for
update using (
        exists (
            select 1
            from public.beatmaps b
            where b.id = beatmap_tags.beatmap_id
                and b.mapper_id = (
                    select auth.uid()
                )
                and b.status = 'UNRANKED'
        )
    ) with check (
        exists (
            select 1
            from public.beatmaps b
            where b.id = beatmap_tags.beatmap_id
                and b.mapper_id = (
                    select auth.uid()
                )
                and b.status = 'UNRANKED'
        )
    );
create policy "Mappers can delete tags for their maps." on public.beatmap_tags for delete using (
    exists (
        select 1
        from public.beatmaps b
        where b.id = beatmap_tags.beatmap_id
            and b.mapper_id = (
                select auth.uid()
            )
            and b.status = 'UNRANKED'
    )
);
-- beatmap_scores
create policy "Beatmap scores are viewable by everyone." on public.beatmap_scores for
select using (true);
create policy "Service role can submit scores." on public.beatmap_scores for
insert to service_role with check (true);
-- comments
create policy "Comments are viewable by everyone." on public.comments for
select using (true);
create policy "Users can post their own comments." on public.comments for
insert with check (
        (
            select auth.uid()
        ) = profile_id
        and not exists (
            select 1
            from public.profiles
            where id = (
                    select auth.uid()
                )
                and (
                    muted_until is not null
                    and muted_until > now()
                )
        )
    );
create policy "Users can update their own comments." on public.comments for
update using (
        (
            select auth.uid()
        ) = profile_id
        and not exists (
            select 1
            from public.profiles
            where id = (
                    select auth.uid()
                )
                and (
                    muted_until is not null
                    and muted_until > now()
                )
        )
    );
    revoke insert, update on public.comments
    from anon,
        authenticated;
    grant insert (resource_type, resource_id, parent_id, profile_id, body) on public.comments to authenticated;
    grant update (body, updated_at) on public.comments to authenticated;
create policy "Users can delete their own comments, admins delete any." on public.comments for delete using (
    (
        select auth.uid()
    ) = profile_id
    or exists (
        select 1
        from public.profiles
        where id = (
                select auth.uid()
            )
            and is_admin = true
    )
);
-- comment_votes
create policy "Comment votes are viewable by everyone." on public.comment_votes for
select using (true);
create policy "Users can vote." on public.comment_votes for
insert with check (
        (
            select auth.uid()
        ) = user_id
    );
create policy "Users can update their own vote." on public.comment_votes for
update using (
        (
            select auth.uid()
        ) = user_id
    );
revoke update on public.comment_votes
from anon,
    authenticated;
grant update (vote) on public.comment_votes to authenticated;
create policy "Users can delete their own vote." on public.comment_votes for delete using (
    (
        select auth.uid()
    ) = user_id
);
-- profile_rank_pp_snapshots
create policy "Rank/PP snapshots are viewable by everyone." on public.profile_rank_pp_snapshots for
select using (true);
-- user_2fa_config
create policy "Users can view their own 2FA config." on public.user_2fa_config for
select using (
        (
            select auth.uid()
        ) = user_id
    );
create policy "Users can update their own 2FA config." on public.user_2fa_config for
update using (
        (
            select auth.uid()
        ) = user_id
    );
create policy "Users can insert their own 2FA config." on public.user_2fa_config for
insert with check (
        (
            select auth.uid()
        ) = user_id
    );
revoke select, insert, update on public.user_2fa_config
from anon,
    authenticated;
grant select (user_id, totp_enabled, webauthn_enabled, created_at, updated_at) on public.user_2fa_config to authenticated;
-- user_webauthn_credentials
create policy "Users can manage their own WebAuthn credentials." on public.user_webauthn_credentials for all using (
    (
        select auth.uid()
    ) = user_id
);
-- auth_handoffs are created and claimed only by trusted Pages Functions.
create policy "Service role can manage auth handoffs." on public.auth_handoffs for all to service_role using (true) with check (true);
revoke all on function public.claim_auth_handoff(uuid, text) from public;
grant execute on function public.claim_auth_handoff(uuid, text) to service_role;
revoke all on function public.cleanup_auth_handoffs() from public;
grant execute on function public.cleanup_auth_handoffs() to service_role;