# Copyright (c) egakareta <team@egakareta.com>.
# Licensed under the GNU AGPLv3 or a proprietary Commercial License.
# See LICENSE and COMMERCIAL.md for details.
name: "Copilot Setup Steps"
on:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, llvm-tools-preview, rustfmt, rust-src
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libudev-dev pkg-config mesa-vulkan-drivers libvulkan1 vulkan-tools
          version: 1.0
      - run: bun install
